### ISSUE TITLE
source_title not being filled in

### ISSUE THREAD

**Issue by mchavezi** [PressForward/PF_Zenodo#18]
Hello,

Thanks for this great plugin. 

I've used this plugin on a site a year ago and the source_title would automatically populate with the posts origins site title. But now I am trying to use on new project and not all meta fields are being imported, including source_title. 

Is this a bug or a setting I am missing?

Thank you,
Michael

**Comment by AramZS** [comment]
@bigbassroller Hi again, did you intend to put this here or in the main PressForward issues? This repo is a specific add on plugin for PressForward.

**Comment by kelle** [comment]
close?
