### ISSUE TITLE
No field for "source title"

### ISSUE THREAD

**Issue by LibrarPotter** [PressForward/PF_Zenodo#8]
The item title and the source title boxes are frequently automatically filling with all the titles for the item: "Source Title: Item title"

Please add helper text (outside of the boxes) for both item title and source title that encourages the publisher to delete the extraneous text that might auto-populate.
The existing helper text under the source title is currently not helpful.  Please change "Override source title" to "Name of site"

**Comment by kelle** [comment]
this is done. close.
